### ISSUE TITLE
Legend?

### ISSUE THREAD

**Issue by smaegol** [zetp/Bar_plot_NC#1]
The legend for colors is missing, it would be nice to see which color is matching which timepoint. Additionaly in 'Data editing', changing the order of columns (by drag&drop)  doesn't work until any of values is edited but after single edit with "Apply changes" any subsequent rearrangments work.  It would be nice to be able to easily rearrange data without the need to edit values.

**Comment by zetp** [comment]
AD legend:
I have implemented the ggEdit package (see "Edit plot with ggEdit" tab and https://github.com/metrumresearchgroup/ggedit) to expand user capabilities of plot editing beyond scope of this app. You can add legend by changing legend position "none" in ggEdit tab. However you would have to most likely change text size after doing so. ggEdit is not perfect and some functionalities are not implemented yet, therefore editing points or error bars does not work well at the moment.

AD Data editing:
Data editing is done with help of rhandsontable package (https://github.com/jrowen/rhandsontable).
It turns out that unfortunately data rearrangements and sorting does not result in change in actual data frame (see: https://github.com/jrowen/rhandsontable/issues/89). I will remove the option to rearrange the columns as it is confusing for the user.
